Implemented groomer login and modified user/groomer registration logic
PetPamper/PetPamper pull request #53
Opened 2024-04-26 02:45 UTC by Shinsaegae

Added logic for groomers to be able to log in (but no groomer home screen yet).

Modified account creation logic slightly to enable users to create both a user and groomer account with a single email.
Also slightly modified UI to accommodate for this.

These don't yet work with Google authentication.

2024-04-26 04:25 UTC, Shinsaegae commented
Still need to fix some merging issues

2024-04-26 05:50 UTC, Chocolat2 commented
Kotlin Formatting checks have failed, I am currently looking into that to try and resolve the issue.

2024-04-26 08:34 UTC, Chocolat2 requested changes
Overall code seems to be working fine on the emulator, however there are no tests designed for the new feature. Additionally, the improvements/modifications on the registration feature may need new or modified tests.

2024-04-26 08:34 UTC, Chocolat2 commented on app/src/main/java/com/android/PetPamper/ui/screen/register/GroomerRegister.kt
>  class GroomerSignUpViewModel {
ViewModel component of the MVVM design pattern is usually in a separate file to enforce separation between the UI, the data formatting and the data processing.

2024-04-26 08:34 UTC, Chocolat2 commented on app/src/main/java/com/android/PetPamper/ui/screen/register/GroomerRegister.kt
>      when (currentStep) {
A match-like structure to handle screen UI changes seems weird to me, is it a common practice on Kotlin/Andriod projects ?

2024-04-26 08:34 UTC, Chocolat2 commented on app/src/main/java/com/android/PetPamper/ui/screen/register/Register.kt
>  class SignUpViewModel {
ViewModel component of the MVVM design pattern is usually in a separate file to enforce separation between the UI, the data formatting and the data processing.

2024-04-26 08:34 UTC, Chocolat2 commented on app/src/main/java/com/android/PetPamper/ui/screen/register/Register.kt
>  fun Register(currentStep1: Int, viewModel: SignUpViewModel, navController: NavController) {
Register.kt seems to be a general implementation to be reused and extended for each specific case, yet GroomerRegister.kt implements another similar logic entirely. Could these be refactored ?

2024-05-01 00:30 UTC, chtidaba approved these changes
Code now passes the CI correctly, it successfully implement the requested functionalities.

Still some little bugs that does not affect the user experience but when registering a user, in the logcat we have an error suggesting that it tries to register the user multiple times. But bug now is fixed. 

for the rest, nothing to suggest, LGTM!

2024-05-01 00:37 UTC, Shinsaegae commented on app/src/main/java/com/android/PetPamper/ui/screen/LoginScreen.kt
> +//                      Button(
Removed the commented code

2024-05-02 16:27 UTC, Chocolat2 commented on app/src/main/java/com/android/PetPamper/ui/screen/register/GroomerRegister.kt
>      when (currentStep) {
The UI change could be handled more efficiently by refactoring the navigation throughout the app, see:
https://developer.android.com/develop/ui/compose/navigation
https://developer.android.com/develop/ui/compose/architecture
https://developer.android.com/guide/navigation
https://github.com/android/nowinandroid

2024-05-02 16:55 UTC, Chocolat2 reviewed
Switch toggle feature looks good, overall app codebase will need to be refactored before adding new features to keep code maintainability and testability.
Test should be implemented more frequently on new (and existing features).

2024-05-02 16:55 UTC, Chocolat2 commented on app/src/main/java/com/android/PetPamper/ui/screen/LoginScreen.kt
>                          firebaseConnection.loginUser(
UI events should be handled in the ViewModel, which itself should delegate data queries and updates to the Model and the data layer.

2024-05-02 16:55 UTC, Chocolat2 commented on app/src/main/java/com/android/PetPamper/ui/screen/register/GroomerRegister.kt
> +  val firebaseConnection = FirebaseConnection()
UI events should be handled in the ViewModel, which itself should delegate data queries and updates to the Model and the data layer.

2024-05-02 16:55 UTC, Chocolat2 commented on app/src/main/java/com/android/PetPamper/ui/screen/register/Register.kt
> +  val firebaseConnection = FirebaseConnection()
UI events should be handled in the ViewModel, which itself should delegate data queries and updates to the Model and the data layer.

2024-05-02 16:55 UTC, Chocolat2 commented on app/src/main/java/com/android/PetPamper/ui/screen/register/Register.kt
> +                colors = ButtonDefaults.buttonColors(Color(0xFF2491DF)),
Colors values can be specified in R.values.color
Theme for he whole app can be specified in R.values.theme

2024-05-02 16:57 UTC, Chocolat2 approved these changes

2024-05-02 16:58 UTC, merged